name: Release Creation

on:
  release:
    types: [published]
permissions:
  contents: write
  pull-requests: write
  actions: write
  deployments: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # get part of the tag after the `v`
      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@d97fbc34ceb64d1f5d95f4dfd6dce33521ccccf5

      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@6287962da9e5b6e68778dc51e840caa03ca84495
        with:
          files: "module.json"
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip

      # Create a zip file with all files required by the module to add to the release
      - run: zip -r ./module.zip module.json README.md LICENSE styles/ scripts/ templates/ lang/ lib/ img/ packs/ assets/ boilerplate/ scss/ languages/

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          artifacts: "./module.json, ./module.zip"
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
      - name: Publish to Foundry VTT packages
        uses: fjogeleit/http-request-action@23ad54bcd1178fcff6a0d17538fa09de3a7f0a4d
        with:
          timeout: 60000
          url: "https://api.foundryvtt.com/_api/packages/release_version/"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json", "Authorization":"${{secrets.FOUNDRY_PACKAGE_RELEASE_TOKEN}}"}'
          data: '{"id": "physical-dice-rolls", "release": { "version": "${{github.event.release.tag_name}}", "manifest": "https://github.com/Rowiz49/physical-dice-rolls/releases/download/${{github.event.release.tag_name}}/module.json", "notes": "https://github.com/Rowiz49/physical-dice-rolls", "compatibility": {"minimum": "11","verified": "13","maximum": ""}}}'
